### ISSUE TITLE
Fix parsing of grades

### ISSUE THREAD

**Issue by clehner** [RocHack/bb#6]
When `bb grades` retrieves grades, there is HTML output in the text stream. Fix the [regexes](https://github.com/RocHack/bb/blob/master/bb#L683) in `bb_grades` to make it output a nicely formatted list of grades.

**Comment by jeremywrnr** [comment]
My output looks good! Plus, now both the manually entered and calculated grades are displayed.

**Comment by clehner** [comment]
:v:
